services:
  bbc_mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    container_name: bbc_api_myslq_container
    environment:
      MYSQL_ROOT_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: Asia/Seoul
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
